// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class NopCommercesuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginwithvalidcredslogout() {
    driver.Navigate().GoToUrl("http://127.0.0.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1233, 725);
    driver.FindElement(By.LinkText("Войти")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).Click();
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    try {
      Thread.Sleep(10);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.LinkText("Log out")).Click();
  }
  [Test]
  public void addnokialumiatocard() {
    driver.Navigate().GoToUrl("http://127.0.0.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1389, 822);
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).Click();
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    driver.FindElement(By.Id("small-searchterms")).Click();
    driver.FindElement(By.Id("small-searchterms")).SendKeys("nokia lumia");
    driver.FindElement(By.CssSelector(".search-box-button")).Click();
    driver.FindElement(By.CssSelector(".product-box-add-to-cart-button")).Click();
    driver.FindElement(By.CssSelector(".cart-label")).Click();
    driver.FindElement(By.LinkText("Log out")).Click();
  }
  [Test]
  public void changequantitygoodsincart() {
    driver.Navigate().GoToUrl("http://127.0.0.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1389, 822);
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).Click();
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    driver.FindElement(By.CssSelector(".cart-label")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Id("itemquantity8")).Click();
    driver.FindElement(By.Id("itemquantity8")).SendKeys("5");
    driver.FindElement(By.CssSelector(".update-cart-button")).Click();
    driver.FindElement(By.LinkText("Log out")).Click();
  }
  [Test]
  public void setuserdata() {
    driver.Navigate().GoToUrl("http://127.0.0.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1389, 822);
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).Click();
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    driver.FindElement(By.LinkText("My account")).Click();
    driver.FindElement(By.Id("gender-female")).Click();
    driver.FindElement(By.Id("FirstName")).Click();
    driver.FindElement(By.Id("FirstName")).SendKeys("Anna");
    driver.FindElement(By.Id("LastName")).Click();
    driver.FindElement(By.Id("LastName")).Click();
    driver.FindElement(By.Id("LastName")).SendKeys("Liubchuk");
    driver.FindElement(By.Id("save-info-button")).Click();
    try {
      Thread.Sleep(30);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.LinkText("Log out")).Click();
  }
}
